version: '3.8'
services:
  reverse-proxy:
    build:
      context: reverse_proxy
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:80
    restart: unless-stopped
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - HOST=${API_HOST}
      - PORT=${API_PORT}
    depends_on:
      - reverse-proxy
