version: '3.8'
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
  api:
    build:
      context: api
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
    depends_on:
      - nginx